# Generated by Django 6.1.1 on 2026-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='materiels/'),
        ),
    ]
